package com.doctorjava.lms.service;

import com.doctorjava.lms.dto.QuestionDtos.*; import com.doctorjava.lms.entity.*; import com.doctorjava.lms.repository.*;
import org.springframework.data.domain.*; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*; import java.math.BigDecimal;

@Service("practiceQuestionService") public class QuestionService {
 private final QuestionRepository questions; private final SubjectRepository subjects; private final TopicRepository topics;
 public QuestionService(QuestionRepository q,SubjectRepository s,TopicRepository t){questions=q;subjects=s;topics=t;}
 @Transactional(readOnly=true) public Page<AdminQuestionResponse> list(String search,int page,int size){ Page<Question> p=search==null||search.isBlank()?questions.findAllByOrderByUpdatedAtDesc(PageRequest.of(page,size)):questions.findByQuestionCodeContainingIgnoreCaseOrQuestionTextContainingIgnoreCaseOrderByUpdatedAtDesc(search,search,PageRequest.of(page,size)); return p.map(this::admin); }
 @Transactional(readOnly=true) public AdminQuestionResponse get(Long id){return admin(questions.findById(id).orElseThrow(()->new NoSuchElementException("Question not found")));}
 @Transactional public AdminQuestionResponse create(QuestionRequest r){
   Subject s=subjects.findById(r.subjectId()).orElseThrow(()->new NoSuchElementException("Subject not found")); Topic t=topics.findById(r.topicId()).orElseThrow(()->new NoSuchElementException("Topic not found"));
   validate(r); Question q=Question.builder().questionCode("Q-"+UUID.randomUUID().toString().substring(0,8).toUpperCase()).type(r.type()).subject(s).topic(t).subtopic(r.subtopic()).difficulty(r.difficulty()).questionText(r.questionText()).codeContent(r.codeContent()).codeLanguage(r.codeLanguage()).explanation(r.explanation()).marks(r.marks()).negativeMarks(r.negativeMarks()).status(parseStatus(r.status())).version(1).createdBy(1L).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build();
   for(int i=0;i<r.options().size();i++){OptionRequest o=r.options().get(i); q.getOptions().add(QuestionOption.builder().question(q).optionKey(o.key()).optionText(o.text()).displayOrder(i+1).correct(o.correct()).build());} questions.save(q); return admin(q);
 }
 @Transactional public AdminQuestionResponse update(Long id,QuestionRequest r){ Question q=questions.findById(id).orElseThrow(()->new NoSuchElementException("Question not found")); validate(r); Subject s=subjects.findById(r.subjectId()).orElseThrow(); Topic t=topics.findById(r.topicId()).orElseThrow(); q.setType(r.type());q.setSubject(s);q.setTopic(t);q.setSubtopic(r.subtopic());q.setDifficulty(r.difficulty());q.setQuestionText(r.questionText());q.setCodeContent(r.codeContent());q.setCodeLanguage(r.codeLanguage());q.setExplanation(r.explanation());q.setMarks(r.marks());q.setNegativeMarks(r.negativeMarks());q.setStatus(parseStatus(r.status()));q.setVersion(q.getVersion()+1);q.setUpdatedAt(LocalDateTime.now());q.getOptions().clear(); for(int i=0;i<4;i++){OptionRequest o=r.options().get(i);q.getOptions().add(QuestionOption.builder().question(q).optionKey(o.key()).optionText(o.text()).displayOrder(i+1).correct(o.correct()).build());} return admin(questions.save(q)); }
 @Transactional public void archive(Long id){Question q=questions.findById(id).orElseThrow(()->new NoSuchElementException("Question not found"));q.setStatus(Question.QuestionStatus.ARCHIVED);q.setUpdatedAt(LocalDateTime.now());}
 public List<Question> published(){return questions.findByStatusOrderByIdAsc(Question.QuestionStatus.PUBLISHED);}
 @Transactional public AdminQuestionResponse updateStatus(Long id, Question.QuestionStatus status){ Question q=questions.findById(id).orElseThrow(()->new NoSuchElementException("Question not found")); q.setStatus(status); q.setUpdatedAt(LocalDateTime.now()); return admin(q); }
 private void validate(QuestionRequest r){ if(r.options().size()!=4||r.options().stream().filter(OptionRequest::correct).count()!=1) throw new IllegalArgumentException("Exactly four options and exactly one correct answer are required"); Set<String> keys=new HashSet<>(); for(OptionRequest o:r.options()){if(!keys.add(o.key()))throw new IllegalArgumentException("Option keys must be unique");} if(r.type()==Question.QuestionType.CODE_OUTPUT&&(r.codeContent()==null||r.codeContent().isBlank()||r.codeLanguage()==null||r.codeLanguage().isBlank()))throw new IllegalArgumentException("Code and language are required for code-output questions"); if(r.type()==Question.QuestionType.TECHNICAL_MCQ&&(r.questionText()==null||r.questionText().isBlank()))throw new IllegalArgumentException("Question text is required for technical MCQ"); }
 private Question.QuestionStatus parseStatus(String s){try{return Question.QuestionStatus.valueOf(s==null?"DRAFT":s);}catch(Exception e){return Question.QuestionStatus.DRAFT;}}
 public AdminQuestionResponse admin(Question q){return new AdminQuestionResponse(q.getId(),q.getQuestionCode(),q.getType().name(),q.getSubject().getId(),q.getSubject().getName(),q.getTopic().getId(),q.getTopic().getName(),q.getSubtopic(),q.getDifficulty().name(),q.getQuestionText(),q.getCodeContent(),q.getCodeLanguage(),q.getExplanation(),q.getMarks(),q.getNegativeMarks(),q.getStatus().name(),q.getOptions().stream().map(o->new AdminOptionResponse(o.getId(),o.getOptionKey(),o.getOptionText(),o.isCorrect())).toList());}
 public StudentQuestionResponse student(Question q){return new StudentQuestionResponse(q.getId(),q.getType().name(),q.getTopic().getName(),q.getDifficulty().name(),q.getQuestionText(),q.getCodeContent(),q.getCodeLanguage(),q.getOptions().stream().map(o->new OptionResponse(o.getId(),o.getOptionKey(),o.getOptionText())).toList());}
}
