export type Question = {
  id: string;
  topic: string;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

export type MockTest = {
  id: string;
  title: string;
  category: string;
  description: string;
  durationMinutes: number;
  marksPerQuestion: number;
  negativeMarks: number;
  passPercentage: number;
  questions: Question[];
};

export const MOCK_TESTS: MockTest[] = [
  {
    id: "core-java",
    title: "Core Java Fundamentals",
    category: "Java",
    description:
      "OOP concepts, collections, exception handling, and multithreading basics.",
    durationMinutes: 15,
    marksPerQuestion: 4,
    negativeMarks: 1,
    passPercentage: 50,
    questions: [
      {
        id: "cj-1",
        topic: "OOP",
        text: "Which of these is not a valid access modifier in Java?",
        options: ["public", "protected", "internal", "private"],
        correctIndex: 2,
        explanation: "Java has public, protected, private and default (no keyword) access modifiers. 'internal' is a C# keyword, not Java.",
      },
      {
        id: "cj-2",
        topic: "OOP",
        text: "Which keyword is used to prevent a class from being inherited?",
        options: ["static", "final", "sealed", "const"],
        correctIndex: 1,
        explanation: "The 'final' keyword, when applied to a class, prevents it from being subclassed.",
      },
      {
        id: "cj-3",
        topic: "Collections",
        text: "Which collection class does not allow duplicate elements?",
        options: ["ArrayList", "LinkedList", "HashSet", "Vector"],
        correctIndex: 2,
        explanation: "HashSet implements the Set interface, which by definition does not permit duplicate elements.",
      },
      {
        id: "cj-4",
        topic: "Collections",
        text: "Which interface must a class implement to be used as a key in a HashMap reliably?",
        options: ["Comparable", "Serializable", "hashCode() and equals()", "Cloneable"],
        correctIndex: 2,
        explanation: "HashMap relies on a well-defined hashCode() and equals() contract to correctly bucket and retrieve keys.",
      },
      {
        id: "cj-5",
        topic: "Exceptions",
        text: "Which of these is a checked exception in Java?",
        options: ["NullPointerException", "ArrayIndexOutOfBoundsException", "IOException", "ArithmeticException"],
        correctIndex: 2,
        explanation: "IOException extends Exception directly (not RuntimeException), making it a checked exception that must be declared or caught.",
      },
      {
        id: "cj-6",
        topic: "Exceptions",
        text: "What happens if a 'finally' block contains a return statement?",
        options: [
          "Compilation error",
          "It overrides any return from the try/catch block",
          "It is ignored",
          "Throws IllegalStateException at runtime",
        ],
        correctIndex: 1,
        explanation: "A return in 'finally' always overrides a pending return or exception from try/catch — considered bad practice for this reason.",
      },
      {
        id: "cj-7",
        topic: "Multithreading",
        text: "Which method is used to make a thread yield the CPU temporarily?",
        options: ["sleep()", "yield()", "wait()", "join()"],
        correctIndex: 1,
        explanation: "Thread.yield() is a hint to the scheduler that the current thread is willing to yield its CPU usage.",
      },
      {
        id: "cj-8",
        topic: "Multithreading",
        text: "Which keyword ensures only one thread can execute a method at a time?",
        options: ["volatile", "synchronized", "transient", "static"],
        correctIndex: 1,
        explanation: "'synchronized' acquires a lock on the object/class, ensuring mutual exclusion for the block or method.",
      },
      {
        id: "cj-9",
        topic: "Core Syntax",
        text: "What is the default value of a boolean instance variable in Java?",
        options: ["true", "false", "null", "0"],
        correctIndex: 1,
        explanation: "Instance boolean fields default to false if not explicitly initialized.",
      },
      {
        id: "cj-10",
        topic: "Core Syntax",
        text: "Which of these correctly overrides equals() alongside hashCode() best practice?",
        options: [
          "Overriding only equals() is always sufficient",
          "Overriding only hashCode() is always sufficient",
          "Both should be overridden together consistently",
          "Neither should ever be overridden",
        ],
        correctIndex: 2,
        explanation: "The equals/hashCode contract requires that equal objects have equal hash codes, so both must be overridden together.",
      },
    ],
  },
  {
    id: "spring-boot",
    title: "Spring Boot & REST APIs",
    category: "Spring Boot",
    description:
      "Dependency injection, REST controllers, JPA, and Spring Security fundamentals.",
    durationMinutes: 15,
    marksPerQuestion: 4,
    negativeMarks: 1,
    passPercentage: 50,
    questions: [
      {
        id: "sb-1",
        topic: "Core Spring",
        text: "Which annotation marks a class as a Spring-managed REST controller?",
        options: ["@Component", "@RestController", "@Service", "@Configuration"],
        correctIndex: 1,
        explanation: "@RestController combines @Controller and @ResponseBody, marking the class as a REST endpoint provider.",
      },
      {
        id: "sb-2",
        topic: "Core Spring",
        text: "What is the primary purpose of Spring's IoC container?",
        options: [
          "Compiling Java bytecode",
          "Managing object creation and dependency injection",
          "Handling HTTP routing only",
          "Replacing the JVM garbage collector",
        ],
        correctIndex: 1,
        explanation: "The Inversion of Control container manages the lifecycle and wiring of beans, injecting dependencies automatically.",
      },
      {
        id: "sb-3",
        topic: "REST APIs",
        text: "Which HTTP method is idempotent and used to fully replace a resource?",
        options: ["POST", "PATCH", "PUT", "DELETE"],
        correctIndex: 2,
        explanation: "PUT is idempotent and conventionally replaces the entire resource at a given URI.",
      },
      {
        id: "sb-4",
        topic: "REST APIs",
        text: "Which annotation binds a method parameter to a URI template variable?",
        options: ["@RequestParam", "@PathVariable", "@RequestBody", "@ModelAttribute"],
        correctIndex: 1,
        explanation: "@PathVariable extracts values from the URI path itself, e.g. /users/{id}.",
      },
      {
        id: "sb-5",
        topic: "Data JPA",
        text: "Which annotation marks a field as the primary key in a JPA entity?",
        options: ["@Column", "@Id", "@GeneratedValue", "@Table"],
        correctIndex: 1,
        explanation: "@Id designates the primary key field of the entity; @GeneratedValue is typically used alongside it for auto-generation.",
      },
      {
        id: "sb-6",
        topic: "Data JPA",
        text: "In Spring Data JPA, what does a method named findByEmailAndStatus do?",
        options: [
          "Nothing, it must be manually implemented",
          "Auto-generates a query filtering by email and status fields",
          "Only works with native SQL",
          "Throws a compilation error",
        ],
        correctIndex: 1,
        explanation: "Spring Data JPA derives queries from method names, so this generates a WHERE email = ? AND status = ? query automatically.",
      },
      {
        id: "sb-7",
        topic: "Security",
        text: "What does Spring Security's @PreAuthorize annotation do?",
        options: [
          "Logs requests before authentication",
          "Evaluates a security expression before method execution",
          "Encrypts request bodies",
          "Registers a new user",
        ],
        correctIndex: 1,
        explanation: "@PreAuthorize evaluates a SpEL security expression before allowing the annotated method to execute.",
      },
      {
        id: "sb-8",
        topic: "Microservices",
        text: "Which pattern helps prevent cascading failures between microservices?",
        options: ["Singleton pattern", "Circuit breaker pattern", "Builder pattern", "Observer pattern"],
        correctIndex: 1,
        explanation: "The circuit breaker pattern (e.g. Resilience4j) stops calls to a failing service, preventing cascading failures.",
      },
      {
        id: "sb-9",
        topic: "Configuration",
        text: "Which file is commonly used for externalized configuration in Spring Boot?",
        options: ["web.xml", "application.properties", "pom.xml", "beans.xml"],
        correctIndex: 1,
        explanation: "application.properties (or application.yml) is Spring Boot's default externalized configuration file.",
      },
      {
        id: "sb-10",
        topic: "Core Spring",
        text: "What is the default scope of a Spring bean?",
        options: ["prototype", "request", "singleton", "session"],
        correctIndex: 2,
        explanation: "By default, Spring beans are singleton-scoped — one shared instance per Spring container.",
      },
    ],
  },
  {
    id: "react-frontend",
    title: "React & Front-End Engineering",
    category: "React",
    description: "Hooks, component lifecycle, state management, and rendering behavior.",
    durationMinutes: 15,
    marksPerQuestion: 4,
    negativeMarks: 1,
    passPercentage: 50,
    questions: [
      {
        id: "rf-1",
        topic: "Hooks",
        text: "Which hook lets you perform side effects in a function component?",
        options: ["useState", "useEffect", "useMemo", "useRef"],
        correctIndex: 1,
        explanation: "useEffect runs side effects (data fetching, subscriptions, DOM manipulation) after render.",
      },
      {
        id: "rf-2",
        topic: "Hooks",
        text: "What does passing an empty dependency array [] to useEffect achieve?",
        options: [
          "Runs the effect on every render",
          "Runs the effect only once after the initial render",
          "Prevents the effect from ever running",
          "Runs the effect only on unmount",
        ],
        correctIndex: 1,
        explanation: "An empty dependency array means the effect has no reactive values to track, so it runs only once after mount.",
      },
      {
        id: "rf-3",
        topic: "State",
        text: "Why should state updates in React be treated as immutable?",
        options: [
          "Mutable updates are faster",
          "React relies on reference comparison to detect changes and re-render",
          "JavaScript objects cannot be mutated",
          "It is only a stylistic convention with no functional impact",
        ],
        correctIndex: 1,
        explanation: "React's reconciliation often compares references; mutating state directly can cause missed re-renders.",
      },
      {
        id: "rf-4",
        topic: "Rendering",
        text: "What is the purpose of the 'key' prop in a list of rendered elements?",
        options: [
          "Styling individual list items",
          "Helping React identify which items changed, were added, or removed",
          "Setting the tab index",
          "Enabling server-side rendering",
        ],
        correctIndex: 1,
        explanation: "Keys give React a stable identity for list items across renders, enabling efficient diffing.",
      },
      {
        id: "rf-5",
        topic: "Rendering",
        text: "Which hook memoizes an expensive computed value between renders?",
        options: ["useCallback", "useMemo", "useContext", "useReducer"],
        correctIndex: 1,
        explanation: "useMemo caches the result of a computation and only recalculates when its dependencies change.",
      },
      {
        id: "rf-6",
        topic: "State Management",
        text: "What problem does the Context API primarily solve?",
        options: [
          "Improving bundle size",
          "Avoiding prop drilling across deeply nested components",
          "Replacing all local component state",
          "Handling HTTP requests",
        ],
        correctIndex: 1,
        explanation: "Context lets you share values across the component tree without manually passing props at every level.",
      },
      {
        id: "rf-7",
        topic: "Component Lifecycle",
        text: "In function components, what replaces componentDidMount and componentWillUnmount together?",
        options: [
          "useState",
          "useEffect with a cleanup function",
          "useLayoutEffect only",
          "useReducer",
        ],
        correctIndex: 1,
        explanation: "A useEffect whose callback returns a cleanup function mirrors both mount and unmount lifecycle behavior.",
      },
      {
        id: "rf-8",
        topic: "Performance",
        text: "Which technique helps avoid unnecessary re-renders of a child component receiving the same props?",
        options: ["React.memo", "useEffect", "PropTypes", "StrictMode"],
        correctIndex: 0,
        explanation: "React.memo memoizes a component, skipping re-render when props are shallowly equal to the previous render.",
      },
      {
        id: "rf-9",
        topic: "Forms",
        text: "What is a 'controlled component' in React forms?",
        options: [
          "A component rendered only on the server",
          "An input whose value is driven by React state",
          "A component that cannot be tested",
          "Any component wrapped in a HOC",
        ],
        correctIndex: 1,
        explanation: "A controlled component's form value is held in and updated via React state, making React the single source of truth.",
      },
      {
        id: "rf-10",
        topic: "Routing",
        text: "In client-side routing, what does dynamic route matching (e.g. /users/:id) allow?",
        options: [
          "Only static pages can be served",
          "Capturing a URL segment as a parameter available to the component",
          "Disabling browser back/forward navigation",
          "Server-only rendering of that route",
        ],
        correctIndex: 1,
        explanation: "Dynamic segments like :id let the router extract a value from the URL and pass it to the matched component.",
      },
    ],
  },
  {
    id: "dsa",
    title: "DSA & Problem Solving",
    category: "DSA",
    description: "Time complexity, arrays, trees, and common algorithmic patterns.",
    durationMinutes: 15,
    marksPerQuestion: 4,
    negativeMarks: 1,
    passPercentage: 50,
    questions: [
      {
        id: "dsa-1",
        topic: "Complexity",
        text: "What is the average time complexity of searching in a balanced binary search tree?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
        correctIndex: 1,
        explanation: "A balanced BST halves the search space at each step, giving O(log n) average-case lookup.",
      },
      {
        id: "dsa-2",
        topic: "Complexity",
        text: "What is the time complexity of accessing an element by index in an array?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"],
        correctIndex: 0,
        explanation: "Arrays support constant-time random access since element addresses are computed directly from the index.",
      },
      {
        id: "dsa-3",
        topic: "Arrays",
        text: "Which technique is commonly used to find a pair with a given sum in a sorted array in O(n)?",
        options: ["Binary search", "Two-pointer technique", "Depth-first search", "Dynamic programming"],
        correctIndex: 1,
        explanation: "Two pointers starting from both ends of a sorted array can find a target-sum pair in a single linear pass.",
      },
      {
        id: "dsa-4",
        topic: "Sorting",
        text: "Which sorting algorithm has the best worst-case time complexity of O(n log n)?",
        options: ["Bubble sort", "Insertion sort", "Merge sort", "Selection sort"],
        correctIndex: 2,
        explanation: "Merge sort guarantees O(n log n) in the worst case due to its divide-and-conquer structure, unlike quicksort's O(n²) worst case.",
      },
      {
        id: "dsa-5",
        topic: "Trees",
        text: "In a binary tree, what does an in-order traversal visit first?",
        options: ["Root, then left, then right", "Left subtree, then root, then right subtree", "Right subtree, then root, then left subtree", "Only leaf nodes"],
        correctIndex: 1,
        explanation: "In-order traversal visits left subtree → root → right subtree, which yields sorted output for a BST.",
      },
      {
        id: "dsa-6",
        topic: "Stacks & Queues",
        text: "Which data structure is best suited for implementing an 'undo' feature?",
        options: ["Queue", "Stack", "Graph", "Hash map"],
        correctIndex: 1,
        explanation: "A stack's LIFO order naturally matches undo behavior — the most recent action is undone first.",
      },
      {
        id: "dsa-7",
        topic: "Dynamic Programming",
        text: "What core idea distinguishes dynamic programming from plain recursion?",
        options: [
          "It never uses recursion",
          "It caches (memoizes) results of overlapping subproblems to avoid recomputation",
          "It only works on sorted arrays",
          "It always uses O(1) space",
        ],
        correctIndex: 1,
        explanation: "DP stores solutions to overlapping subproblems, trading space for avoiding repeated computation.",
      },
      {
        id: "dsa-8",
        topic: "Graphs",
        text: "Which traversal algorithm is typically used to find the shortest path in an unweighted graph?",
        options: ["Depth-first search", "Breadth-first search", "In-order traversal", "Quick sort"],
        correctIndex: 1,
        explanation: "BFS explores nodes level by level, guaranteeing the shortest path in terms of edge count for unweighted graphs.",
      },
      {
        id: "dsa-9",
        topic: "Hashing",
        text: "What is the average time complexity for insertion in a well-implemented hash map?",
        options: ["O(1)", "O(log n)", "O(n)", "O(n^2)"],
        correctIndex: 0,
        explanation: "With a good hash function and low load factor, hash map insertion is O(1) on average.",
      },
      {
        id: "dsa-10",
        topic: "Recursion",
        text: "What can happen if a recursive function has no correctly reachable base case?",
        options: [
          "It runs faster",
          "It causes a stack overflow from infinite recursion",
          "It automatically converts to iteration",
          "Nothing, Java optimizes it automatically",
        ],
        correctIndex: 1,
        explanation: "Without a reachable base case, recursive calls never terminate, eventually exhausting the call stack.",
      },
    ],
  },
];

export function getTestById(id: string): MockTest | undefined {
  return MOCK_TESTS.find((t) => t.id === id);
}
